[package]
name = "openresolvium"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
chrono = "0.4"
reqwest = { version = "0.11", features = ["blocking"] }
vnc-rs = "0.5.2"
image = "0.24"
anyhow = "1.0"
minifb = "0.25.0"
tracing = "0.1"